import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // Old classes mapped to new theme
        deep: "#0b1326",
        navy: "#131b2e",
        card: "#171f33",
        border: "rgba(76,215,246,0.15)",
        teal: {
          DEFAULT: "#4cd7f6",
          bright: "#acedff",
          dim: "#06b6d4",
          glow: "rgba(76,215,246,0.3)",
        },
        copper: "#1bbd85",
        muted: "#869397",
        soft: "#bcc9cd",
        // New theme colors from the provided HTML
        "on-secondary": "#002a78",
        "on-tertiary": "#003824",
        "on-tertiary-fixed": "#002113",
        "on-error": "#690005",
        "tertiary": "#4edea3",
        "on-primary-fixed": "#001f26",
        "primary": "#4cd7f6",
        "surface-dim": "#0b1326",
        "on-background": "#dae2fd",
        "error": "#ffb4ab",
        "on-error-container": "#ffdad6",
        "error-container": "#93000a",
        "surface-container-low": "#131b2e",
        "surface-container-lowest": "#060e20",
        "secondary-container": "#0053db",
        "primary-fixed-dim": "#4cd7f6",
        "surface-container-highest": "#2d3449",
        "surface-container-high": "#222a3d",
        "primary-fixed": "#acedff",
        "on-secondary-fixed": "#00174b",
        "on-surface": "#dae2fd",
        "primary-container": "#06b6d4",
        "outline": "#869397",
        "tertiary-container": "#1bbd85",
        "on-secondary-fixed-variant": "#003ea8",
        "on-tertiary-fixed-variant": "#005236",
        "on-primary-container": "#00424f",
        "outline-variant": "#3d494c",
        "secondary-fixed-dim": "#b4c5ff",
        "background": "#0b1326",
        "secondary": "#b4c5ff",
        "surface": "#0b1326",
        "surface-variant": "#2d3449",
        "on-primary-fixed-variant": "#004e5c",
        "surface-container": "#171f33",
        "inverse-on-surface": "#283044",
        "tertiary-fixed-dim": "#4edea3",
        "on-primary": "#003640",
        "surface-bright": "#31394d",
        "inverse-primary": "#00687a",
        "on-tertiary-container": "#00452e",
        "inverse-surface": "#dae2fd",
        "secondary-fixed": "#dbe1ff",
        "on-secondary-container": "#cdd7ff",
        "tertiary-fixed": "#6ffbbe",
        "surface-tint": "#4cd7f6",
        "on-surface-variant": "#bcc9cd"
      },
      fontFamily: {
        sans: ["var(--font-inter)", "Inter", "system-ui", "sans-serif"],
        display: ["var(--font-syne)", "Syne", "sans-serif"],
        mono: ["var(--font-jetbrains)", "JetBrains Mono", "monospace"],
      },
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "gradient-conic": "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
        "hero-glow": "radial-gradient(ellipse 80% 50% at 50% 0%, rgba(76,215,246,0.15) 0%, transparent 60%)",
        "card-glow": "radial-gradient(circle at 50% 0%, rgba(76,215,246,0.08) 0%, transparent 60%)",
        "teal-gradient": "linear-gradient(135deg, #4cd7f6, #06b6d4)",
        "dark-gradient": "linear-gradient(180deg, #131b2e 0%, #0b1326 100%)",
      },
      animation: {
        "float": "float 6s ease-in-out infinite",
        "float-slow": "float 9s ease-in-out infinite",
        "pulse-slow": "pulse 4s ease-in-out infinite",
        "spin-slow": "spin 20s linear infinite",
        "marquee": "marquee 25s linear infinite",
        "marquee-reverse": "marquee 25s linear infinite reverse",
        "gradient-shift": "gradientShift 8s ease infinite",
        "blink": "blink 1.5s ease-in-out infinite",
      },
      keyframes: {
        float: {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-20px)" },
        },
        marquee: {
          "0%": { transform: "translateX(0%)" },
          "100%": { transform: "translateX(-50%)" },
        },
        gradientShift: {
          "0%, 100%": { backgroundPosition: "0% 50%" },
          "50%": { backgroundPosition: "100% 50%" },
        },
        blink: {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.3" },
        },
      },
      boxShadow: {
        "teal-sm": "0 0 20px rgba(76,215,246,0.2)",
        "teal-md": "0 0 40px rgba(76,215,246,0.3)",
        "teal-lg": "0 0 80px rgba(76,215,246,0.4)",
        "card": "0 4px 40px rgba(0,0,0,0.4), inset 0 1px 0 rgba(255,255,255,0.04)",
      },
    },
  },
  plugins: [],
};
export default config;
